export const GROUNDED_ACTIVITIES = [
  { text: "早點洗澡，洗掉一身疲憊", category: "rest" },
  { text: "靜心刷一份抹茶，感受苦後的甘甜", category: "drink" },
  { text: "多吃水果，補充維他命 C", category: "eat" },
  { text: "今天早睡十分鐘，夢裡什麼都有", category: "rest" },
  { text: "整理一下亂糟糟的桌面", category: "clean" },
  { text: "給想念已久的朋友傳個貼圖", category: "happy" },
  { text: "買一束喜歡的花送給自己", category: "happy" },
  { text: "在陽台發呆五分鐘，深呼吸", category: "rest" },
  { text: "把購物車裡猶豫很久的東西結帳吧", category: "happy" },
  { text: "聽一首節奏輕快的歌，偷偷扭一下", category: "happy" },
  { text: "換上一套乾淨舒服的睡衣", category: "rest" },
  { text: "認真刷牙三分鐘，保護牙齒", category: "clean" },
  { text: "吃一頓熱騰騰的火鍋", category: "eat" },
  { text: "遠離手機一小時，享受清靜", category: "rest" },
  { text: "修剪一下指甲，清爽出發", category: "clean" },
  { text: "喝一杯溫熱的蜂蜜水", category: "drink" },
  { text: "對鏡子裡的自己笑一個", category: "happy" },
  { text: "今天不看任何負面新聞", category: "happy" },
  { text: "去公園踩踩草地，感受大地", category: "outdoor" },
  { text: "點一份平時捨不得點的高級外送", category: "eat" },
  { text: "把被子拿出去曬曬太陽", category: "clean" },
  { text: "寫下三件今天值得感謝的小事", category: "happy" },
  { text: "稱讚身邊的人一件小事，給別人一點自信", category: "rest" },
  { text: "換個新的手機桌布，換個心情", category: "happy" },
  { text: "練習深呼吸十次，放空大腦", category: "rest" },
  { text: "吃一顆甜甜的巧克力", category: "eat" },
  { text: "把鞋櫃裡的鞋子擺整齊", category: "clean" },
  { text: "今天不熬夜，十一點前躺平", category: "rest" },
  { text: "去便利商店買個新品嚐鮮", category: "eat" },
  { text: "認真洗臉，感受水的溫度", category: "clean" },
  { text: "穿上那件最顯瘦的衣服", category: "happy" },
  { text: "給陽台的植物澆澆水", category: "outdoor" },
  { text: "今天多喝水，至少 1500cc", category: "drink" },
  { text: "買個可愛的小文具", category: "happy" },
  { text: "在筆記本上隨手塗鴉", category: "happy" },
  { text: "今天不滑社群軟體，專注當下", category: "rest" },
  { text: "吃一碗熱呼呼的拉麵", category: "eat" },
  { text: "換個舒服的枕頭套", category: "rest" },
  { text: "看看punch小猴子今天在做什麼?", category: "happy" },
  { text: "去書店翻翻充滿新鮮感的書", category: "outdoor" },
  { text: "把過期的發票清一清", category: "clean" },
  { text: "喝一杯現磨的咖啡", category: "drink" },
  { text: "今天不抱怨，想想幸運的小事", category: "happy" },
  { text: "練習一個新的伸展動作", category: "rest" },
  { text: "把耳機音量調小一點，保護耳朵", category: "rest" },
  { text: "吃一顆酸酸甜甜的軟糖", category: "eat" },
  { text: "今天不吃加工食品，吃原形食物", category: "eat" },
  { text: "去操場走兩圈，散散心", category: "outdoor" },
  { text: "把錢包裡的收據整理好", category: "clean" },
  { text: "今天對同事說聲辛苦了", category: "happy" },
  { text: "看一場午夜場電影", category: "rest" },
  { text: "換個洗髮精的味道，換個感覺", category: "rest" },
  { text: "今天不喝含糖飲料（除了抹茶）", category: "drink" },
  { text: "去超市買食材，自己煮一餐", category: "eat" },
  { text: "把舊衣服整理出來捐掉", category: "clean" },
  { text: "今天多站一會兒，別一直坐著", category: "rest" },
  { text: "喝一碗暖胃的紅豆湯", category: "eat" },
  { text: "在睡前看五頁書", category: "rest" },
  { text: "今天不跟別人比較，你就是你", category: "happy" },
  { text: "練習冥想三分鐘", category: "rest" },
  { text: "把電腦螢幕擦乾淨", category: "clean" },
  { text: "今天多讚美別人一次", category: "happy" },
  { text: "去海邊聽聽浪聲", category: "outdoor" },
  { text: "買個好吃的甜甜圈", category: "eat" },
  { text: "在洗澡時大聲唱歌", category: "happy" },
  { text: "今天不看工作訊息，徹底放假", category: "rest" },
  { text: "把指甲油塗成喜歡的顏色", category: "happy" },
  { text: "去花市逛逛，感受生命力", category: "outdoor" },
  { text: "吃一塊剛出爐的麵包", category: "eat" },
  { text: "今天多微笑，好運自然來", category: "happy" },
  { text: "練習寫毛筆字或鋼筆字", category: "happy" },
  { text: "把房間的燈光調暖一點", category: "rest" },
  { text: "今天不吃宵夜，讓腸胃休息", category: "eat" },
  { text: "去爬個小山，看看遠方", category: "outdoor" },
  { text: "買個舒服的香氛蠟燭", category: "rest" },
  { text: "在窗邊看夕陽落下", category: "outdoor" },
  { text: "今天多聽少說，用心觀察", category: "happy" },
  { text: "練習一個簡單的手工藝", category: "happy" },
  { text: "把手機裡的垃圾照片刪一刪", category: "clean" },
  { text: "今天對家人說聲我愛你", category: "happy" },
  { text: "去游泳池泡泡水", category: "outdoor" },
  { text: "吃一盤清爽的沙拉", category: "eat" },
  { text: "在睡前泡個腳，促進循環", category: "rest" },
  { text: "今天不生氣，保持平和", category: "happy" },
  { text: "練習用左手刷牙，挑戰大腦", category: "happy" },
  { text: "把梳妝台整理得亮晶晶", category: "clean" },
  { text: "今天多走路，少搭電梯", category: "outdoor" },
  { text: "喝一杯現打的果汁", category: "drink" },
  { text: "在草地上野餐，吹吹風", category: "outdoor" },
  { text: "今天不糾結過去，展望未來", category: "happy" },
  { text: "練習一個新的廚藝技巧", category: "eat" },
  { text: "把書架上的灰塵撣一撣", category: "clean" },
  { text: "今天多給自己一點掌聲", category: "happy" },
  { text: "去美術館看場展覽", category: "outdoor" },
  { text: "買個質感好的杯子", category: "happy" },
  { text: "早睡早起身體好", category: "rest" },
  { text: "今天不焦慮，一切都是最好的安排", category: "happy" },
  { text: "練習瑜珈五分鐘", category: "rest" },
  { text: "把鑰匙圈換成可愛的樣式", category: "happy" },
  { text: "今天對世界溫柔以待", category: "happy" }
];

export const LUCKY_ITEMS = [
  "對齊的雲朵", "巷口貓咪的哈欠", "有梳頭的早晨", "出水順暢的藍色原子筆",
  "摺得像藝術品的發票", "乾爽舒適的鞋底", "播到副歌的收音機", "溫熱且完美的溏心蛋",
  "剛剪完指甲的清爽感", "順滑如新的耳機線（奇蹟）", "有座位的公車最後一排", "窗台上剛冒出的小新芽",
  "潔白如新的襯衫", "亮起的橘色路燈", "完整的蒲公英", "入座即食的巷口麵攤",
  "裝滿冰塊的氣泡水聲", "剛撕下的那一頁日曆", "清晰透亮的浴室鏡子", "滿格的手機電量",
  "完整的完美落葉", "對齊的磁磚縫隙", "金黃酥脆的吐司邊", "有零錢的舊外套口袋",
  "堅韌耐用的自動鉛筆芯", "晴朗的下班十分鐘", "純淨的全新筆記本第一頁", "有陽光的午後窗邊位",
  "安穩在手的雨傘", "穩定的地下室網路", "完好的沙發角落", "有熱水的蓮蓬頭",
  "成雙成對的耳環", "亮著燈的深夜食堂", "平整的演唱會門票", "順暢的回家路",
  "乾爽的實體書頁", "有位子的捷運博愛座旁", "運作正常的藍牙耳機盒", "有微風的傍晚河堤",
  "陪伴到最後的護唇膏", "安靜的咖啡廳座位", "挺括的乾淨襯衫", "有星星的城市夜空",
  "乖乖待在手腕上的髮圈", "包場般的電影院最後一排", "亮白的鍵盤", "有座位的早餐店窗台",
  "珍藏舊照片的隨身碟", "專屬空間的自助洗衣店", "如新的旅行地圖", "有陽光的週一早晨",
  "隨手可得的指甲剪", "結帳神速的便利商店", "對齊的書架邊緣", "乾爽的信箱信件",
  "有座位的醫務室長椅", "潔淨的帆布鞋頭", "有蟬鳴的午後樹下", "火光穩定的打火機",
  "寬敞的健身房淋浴間", "記憶深刻的電影海報", "有彩虹的雨後天橋", "餘額充足的悠遊卡",
  "陽光明媚的野餐日", "潔淨如新的白板", "有座位的圖書館角落", "安穩待在夾層的鑰匙",
  "安靜的老舊電梯", "保存完好的舊照片", "有陽光的曬衣場", "隨時待命的眼鏡布",
  "寧靜的深夜超商", "素雅潔淨的淺色地毯", "有座位的候車亭", "安穩在位的耳機轉接頭",
  "清幽的清晨街道", "最喜歡的那件衣服", "有陽光的辦公桌", "守護回憶的記憶卡"
];
